version: '3'
services:
  postgres:
    platform: linux/x86_64
    image: postgres:14
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - '5432:5432'
