// Code generated by ogen, DO NOT EDIT.

package api

type ApiKeyHeader struct {
	APIKey string
}

// GetAPIKey returns the value of APIKey.
func (s ApiKeyHeader) GetAPIKey() string {
	return s.APIKey
}

// SetAPIKey sets the value of APIKey.
func (s *ApiKeyHeader) SetAPIKey(val string) {
	s.APIKey = val
}

type ApiKeyParam struct {
	APIKey string
}

// GetAPIKey returns the value of APIKey.
func (s ApiKeyParam) GetAPIKey() string {
	return s.APIKey
}

// SetAPIKey sets the value of APIKey.
func (s *ApiKeyParam) SetAPIKey(val string) {
	s.APIKey = val
}

type Bearer struct {
	Token string
}

// GetToken returns the value of Token.
func (s Bearer) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *Bearer) SetToken(val string) {
	s.Token = val
}

// Ref: #/components/schemas/CreateFunctionBody
type CreateFunctionBody struct {
	Slug      string  `json:"slug"`
	Name      string  `json:"name"`
	Body      string  `json:"body"`
	VerifyJwt OptBool `json:"verify_jwt"`
}

// GetSlug returns the value of Slug.
func (s CreateFunctionBody) GetSlug() string {
	return s.Slug
}

// GetName returns the value of Name.
func (s CreateFunctionBody) GetName() string {
	return s.Name
}

// GetBody returns the value of Body.
func (s CreateFunctionBody) GetBody() string {
	return s.Body
}

// GetVerifyJwt returns the value of VerifyJwt.
func (s CreateFunctionBody) GetVerifyJwt() OptBool {
	return s.VerifyJwt
}

// SetSlug sets the value of Slug.
func (s *CreateFunctionBody) SetSlug(val string) {
	s.Slug = val
}

// SetName sets the value of Name.
func (s *CreateFunctionBody) SetName(val string) {
	s.Name = val
}

// SetBody sets the value of Body.
func (s *CreateFunctionBody) SetBody(val string) {
	s.Body = val
}

// SetVerifyJwt sets the value of VerifyJwt.
func (s *CreateFunctionBody) SetVerifyJwt(val OptBool) {
	s.VerifyJwt = val
}

// CreateFunctionForbidden is response for CreateFunction operation.
type CreateFunctionForbidden struct{}

func (*CreateFunctionForbidden) createFunctionRes() {}

// CreateFunctionInternalServerError is response for CreateFunction operation.
type CreateFunctionInternalServerError struct{}

func (*CreateFunctionInternalServerError) createFunctionRes() {}

// Ref: #/components/schemas/CreateOrganizationBody
type CreateOrganizationBody struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s CreateOrganizationBody) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *CreateOrganizationBody) SetName(val string) {
	s.Name = val
}

// CreateOrganizationInternalServerError is response for CreateOrganization operation.
type CreateOrganizationInternalServerError struct{}

func (*CreateOrganizationInternalServerError) createOrganizationRes() {}

// Ref: #/components/schemas/CreateProjectBody
type CreateProjectBody struct {
	DbPass         string                  `json:"db_pass"`
	Name           string                  `json:"name"`
	OrganizationID string                  `json:"organization_id"`
	Plan           CreateProjectBodyPlan   `json:"plan"`
	Region         CreateProjectBodyRegion `json:"region"`
	KpsEnabled     OptBool                 `json:"kps_enabled"`
}

// GetDbPass returns the value of DbPass.
func (s CreateProjectBody) GetDbPass() string {
	return s.DbPass
}

// GetName returns the value of Name.
func (s CreateProjectBody) GetName() string {
	return s.Name
}

// GetOrganizationID returns the value of OrganizationID.
func (s CreateProjectBody) GetOrganizationID() string {
	return s.OrganizationID
}

// GetPlan returns the value of Plan.
func (s CreateProjectBody) GetPlan() CreateProjectBodyPlan {
	return s.Plan
}

// GetRegion returns the value of Region.
func (s CreateProjectBody) GetRegion() CreateProjectBodyRegion {
	return s.Region
}

// GetKpsEnabled returns the value of KpsEnabled.
func (s CreateProjectBody) GetKpsEnabled() OptBool {
	return s.KpsEnabled
}

// SetDbPass sets the value of DbPass.
func (s *CreateProjectBody) SetDbPass(val string) {
	s.DbPass = val
}

// SetName sets the value of Name.
func (s *CreateProjectBody) SetName(val string) {
	s.Name = val
}

// SetOrganizationID sets the value of OrganizationID.
func (s *CreateProjectBody) SetOrganizationID(val string) {
	s.OrganizationID = val
}

// SetPlan sets the value of Plan.
func (s *CreateProjectBody) SetPlan(val CreateProjectBodyPlan) {
	s.Plan = val
}

// SetRegion sets the value of Region.
func (s *CreateProjectBody) SetRegion(val CreateProjectBodyRegion) {
	s.Region = val
}

// SetKpsEnabled sets the value of KpsEnabled.
func (s *CreateProjectBody) SetKpsEnabled(val OptBool) {
	s.KpsEnabled = val
}

type CreateProjectBodyPlan string

const (
	CreateProjectBodyPlanFree CreateProjectBodyPlan = "free"
	CreateProjectBodyPlanPro  CreateProjectBodyPlan = "pro"
)

type CreateProjectBodyRegion string

const (
	CreateProjectBodyRegionUsMinusEastMinus1      CreateProjectBodyRegion = "us-east-1"
	CreateProjectBodyRegionUsMinusWestMinus1      CreateProjectBodyRegion = "us-west-1"
	CreateProjectBodyRegionApMinusSoutheastMinus1 CreateProjectBodyRegion = "ap-southeast-1"
	CreateProjectBodyRegionApMinusNortheastMinus1 CreateProjectBodyRegion = "ap-northeast-1"
	CreateProjectBodyRegionApMinusNortheastMinus2 CreateProjectBodyRegion = "ap-northeast-2"
	CreateProjectBodyRegionApMinusSoutheastMinus2 CreateProjectBodyRegion = "ap-southeast-2"
	CreateProjectBodyRegionEuMinusWestMinus1      CreateProjectBodyRegion = "eu-west-1"
	CreateProjectBodyRegionEuMinusWestMinus2      CreateProjectBodyRegion = "eu-west-2"
	CreateProjectBodyRegionEuMinusCentralMinus1   CreateProjectBodyRegion = "eu-central-1"
	CreateProjectBodyRegionCaMinusCentralMinus1   CreateProjectBodyRegion = "ca-central-1"
	CreateProjectBodyRegionApMinusSouthMinus1     CreateProjectBodyRegion = "ap-south-1"
	CreateProjectBodyRegionSaMinusEastMinus1      CreateProjectBodyRegion = "sa-east-1"
)

// Ref: #/components/schemas/CreateSecretBody
type CreateSecretBody struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// GetName returns the value of Name.
func (s CreateSecretBody) GetName() string {
	return s.Name
}

// GetValue returns the value of Value.
func (s CreateSecretBody) GetValue() string {
	return s.Value
}

// SetName sets the value of Name.
func (s *CreateSecretBody) SetName(val string) {
	s.Name = val
}

// SetValue sets the value of Value.
func (s *CreateSecretBody) SetValue(val string) {
	s.Value = val
}

// CreateSecretsCreated is response for CreateSecrets operation.
type CreateSecretsCreated struct{}

func (*CreateSecretsCreated) createSecretsRes() {}

// CreateSecretsForbidden is response for CreateSecrets operation.
type CreateSecretsForbidden struct{}

func (*CreateSecretsForbidden) createSecretsRes() {}

// CreateSecretsInternalServerError is response for CreateSecrets operation.
type CreateSecretsInternalServerError struct{}

func (*CreateSecretsInternalServerError) createSecretsRes() {}

// DeleteFunctionForbidden is response for DeleteFunction operation.
type DeleteFunctionForbidden struct{}

func (*DeleteFunctionForbidden) deleteFunctionRes() {}

// DeleteFunctionInternalServerError is response for DeleteFunction operation.
type DeleteFunctionInternalServerError struct{}

func (*DeleteFunctionInternalServerError) deleteFunctionRes() {}

// DeleteFunctionOK is response for DeleteFunction operation.
type DeleteFunctionOK struct{}

func (*DeleteFunctionOK) deleteFunctionRes() {}

// DeleteSecretsForbidden is response for DeleteSecrets operation.
type DeleteSecretsForbidden struct{}

func (*DeleteSecretsForbidden) deleteSecretsRes() {}

// DeleteSecretsInternalServerError is response for DeleteSecrets operation.
type DeleteSecretsInternalServerError struct{}

func (*DeleteSecretsInternalServerError) deleteSecretsRes() {}

type DeleteSecretsOK struct{}

func (*DeleteSecretsOK) deleteSecretsRes() {}

// Ref: #/components/schemas/FunctionResponse
type FunctionResponse struct {
	ID        string                 `json:"id"`
	Slug      string                 `json:"slug"`
	Name      string                 `json:"name"`
	Status    FunctionResponseStatus `json:"status"`
	Version   float64                `json:"version"`
	CreatedAt float64                `json:"created_at"`
	UpdatedAt float64                `json:"updated_at"`
	VerifyJwt OptBool                `json:"verify_jwt"`
}

// GetID returns the value of ID.
func (s FunctionResponse) GetID() string {
	return s.ID
}

// GetSlug returns the value of Slug.
func (s FunctionResponse) GetSlug() string {
	return s.Slug
}

// GetName returns the value of Name.
func (s FunctionResponse) GetName() string {
	return s.Name
}

// GetStatus returns the value of Status.
func (s FunctionResponse) GetStatus() FunctionResponseStatus {
	return s.Status
}

// GetVersion returns the value of Version.
func (s FunctionResponse) GetVersion() float64 {
	return s.Version
}

// GetCreatedAt returns the value of CreatedAt.
func (s FunctionResponse) GetCreatedAt() float64 {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s FunctionResponse) GetUpdatedAt() float64 {
	return s.UpdatedAt
}

// GetVerifyJwt returns the value of VerifyJwt.
func (s FunctionResponse) GetVerifyJwt() OptBool {
	return s.VerifyJwt
}

// SetID sets the value of ID.
func (s *FunctionResponse) SetID(val string) {
	s.ID = val
}

// SetSlug sets the value of Slug.
func (s *FunctionResponse) SetSlug(val string) {
	s.Slug = val
}

// SetName sets the value of Name.
func (s *FunctionResponse) SetName(val string) {
	s.Name = val
}

// SetStatus sets the value of Status.
func (s *FunctionResponse) SetStatus(val FunctionResponseStatus) {
	s.Status = val
}

// SetVersion sets the value of Version.
func (s *FunctionResponse) SetVersion(val float64) {
	s.Version = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *FunctionResponse) SetCreatedAt(val float64) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *FunctionResponse) SetUpdatedAt(val float64) {
	s.UpdatedAt = val
}

// SetVerifyJwt sets the value of VerifyJwt.
func (s *FunctionResponse) SetVerifyJwt(val OptBool) {
	s.VerifyJwt = val
}

func (*FunctionResponse) createFunctionRes() {}
func (*FunctionResponse) updateFunctionRes() {}

type FunctionResponseStatus string

const (
	FunctionResponseStatusACTIVE    FunctionResponseStatus = "ACTIVE"
	FunctionResponseStatusREMOVED   FunctionResponseStatus = "REMOVED"
	FunctionResponseStatusTHROTTLED FunctionResponseStatus = "THROTTLED"
)

// Ref: #/components/schemas/FunctionSlugResponse
type FunctionSlugResponse struct {
	ID        string                     `json:"id"`
	Slug      string                     `json:"slug"`
	Name      string                     `json:"name"`
	Status    FunctionSlugResponseStatus `json:"status"`
	Version   float64                    `json:"version"`
	CreatedAt float64                    `json:"created_at"`
	UpdatedAt float64                    `json:"updated_at"`
	VerifyJwt OptBool                    `json:"verify_jwt"`
	Body      OptString                  `json:"body"`
}

// GetID returns the value of ID.
func (s FunctionSlugResponse) GetID() string {
	return s.ID
}

// GetSlug returns the value of Slug.
func (s FunctionSlugResponse) GetSlug() string {
	return s.Slug
}

// GetName returns the value of Name.
func (s FunctionSlugResponse) GetName() string {
	return s.Name
}

// GetStatus returns the value of Status.
func (s FunctionSlugResponse) GetStatus() FunctionSlugResponseStatus {
	return s.Status
}

// GetVersion returns the value of Version.
func (s FunctionSlugResponse) GetVersion() float64 {
	return s.Version
}

// GetCreatedAt returns the value of CreatedAt.
func (s FunctionSlugResponse) GetCreatedAt() float64 {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s FunctionSlugResponse) GetUpdatedAt() float64 {
	return s.UpdatedAt
}

// GetVerifyJwt returns the value of VerifyJwt.
func (s FunctionSlugResponse) GetVerifyJwt() OptBool {
	return s.VerifyJwt
}

// GetBody returns the value of Body.
func (s FunctionSlugResponse) GetBody() OptString {
	return s.Body
}

// SetID sets the value of ID.
func (s *FunctionSlugResponse) SetID(val string) {
	s.ID = val
}

// SetSlug sets the value of Slug.
func (s *FunctionSlugResponse) SetSlug(val string) {
	s.Slug = val
}

// SetName sets the value of Name.
func (s *FunctionSlugResponse) SetName(val string) {
	s.Name = val
}

// SetStatus sets the value of Status.
func (s *FunctionSlugResponse) SetStatus(val FunctionSlugResponseStatus) {
	s.Status = val
}

// SetVersion sets the value of Version.
func (s *FunctionSlugResponse) SetVersion(val float64) {
	s.Version = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *FunctionSlugResponse) SetCreatedAt(val float64) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *FunctionSlugResponse) SetUpdatedAt(val float64) {
	s.UpdatedAt = val
}

// SetVerifyJwt sets the value of VerifyJwt.
func (s *FunctionSlugResponse) SetVerifyJwt(val OptBool) {
	s.VerifyJwt = val
}

// SetBody sets the value of Body.
func (s *FunctionSlugResponse) SetBody(val OptString) {
	s.Body = val
}

func (*FunctionSlugResponse) getFunctionRes() {}

type FunctionSlugResponseStatus string

const (
	FunctionSlugResponseStatusACTIVE    FunctionSlugResponseStatus = "ACTIVE"
	FunctionSlugResponseStatusREMOVED   FunctionSlugResponseStatus = "REMOVED"
	FunctionSlugResponseStatusTHROTTLED FunctionSlugResponseStatus = "THROTTLED"
)

// GetConfigForbidden is response for GetConfig operation.
type GetConfigForbidden struct{}

func (*GetConfigForbidden) getConfigRes() {}

// GetConfigInternalServerError is response for GetConfig operation.
type GetConfigInternalServerError struct{}

func (*GetConfigInternalServerError) getConfigRes() {}

type GetConfigOK struct{}

func (*GetConfigOK) getConfigRes() {}

// GetFunctionForbidden is response for GetFunction operation.
type GetFunctionForbidden struct{}

func (*GetFunctionForbidden) getFunctionRes() {}

// GetFunctionInternalServerError is response for GetFunction operation.
type GetFunctionInternalServerError struct{}

func (*GetFunctionInternalServerError) getFunctionRes() {}

// GetFunctionsForbidden is response for GetFunctions operation.
type GetFunctionsForbidden struct{}

func (*GetFunctionsForbidden) getFunctionsRes() {}

// GetFunctionsInternalServerError is response for GetFunctions operation.
type GetFunctionsInternalServerError struct{}

func (*GetFunctionsInternalServerError) getFunctionsRes() {}

type GetFunctionsOKApplicationJSON []FunctionResponse

func (GetFunctionsOKApplicationJSON) getFunctionsRes() {}

// GetOrganizationsInternalServerError is response for GetOrganizations operation.
type GetOrganizationsInternalServerError struct{}

func (*GetOrganizationsInternalServerError) getOrganizationsRes() {}

type GetOrganizationsOKApplicationJSON []OrganizationResponse

func (GetOrganizationsOKApplicationJSON) getOrganizationsRes() {}

// GetSecretsForbidden is response for GetSecrets operation.
type GetSecretsForbidden struct{}

func (*GetSecretsForbidden) getSecretsRes() {}

// GetSecretsInternalServerError is response for GetSecrets operation.
type GetSecretsInternalServerError struct{}

func (*GetSecretsInternalServerError) getSecretsRes() {}

type GetSecretsOKApplicationJSON []SecretResponse

func (GetSecretsOKApplicationJSON) getSecretsRes() {}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/OrganizationResponse
type OrganizationResponse struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// GetID returns the value of ID.
func (s OrganizationResponse) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s OrganizationResponse) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *OrganizationResponse) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *OrganizationResponse) SetName(val string) {
	s.Name = val
}

func (*OrganizationResponse) createOrganizationRes() {}

// Ref: #/components/schemas/ProjectResponse
type ProjectResponse struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
	Name           string `json:"name"`
	Region         string `json:"region"`
	CreatedAt      string `json:"created_at"`
}

// GetID returns the value of ID.
func (s ProjectResponse) GetID() string {
	return s.ID
}

// GetOrganizationID returns the value of OrganizationID.
func (s ProjectResponse) GetOrganizationID() string {
	return s.OrganizationID
}

// GetName returns the value of Name.
func (s ProjectResponse) GetName() string {
	return s.Name
}

// GetRegion returns the value of Region.
func (s ProjectResponse) GetRegion() string {
	return s.Region
}

// GetCreatedAt returns the value of CreatedAt.
func (s ProjectResponse) GetCreatedAt() string {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *ProjectResponse) SetID(val string) {
	s.ID = val
}

// SetOrganizationID sets the value of OrganizationID.
func (s *ProjectResponse) SetOrganizationID(val string) {
	s.OrganizationID = val
}

// SetName sets the value of Name.
func (s *ProjectResponse) SetName(val string) {
	s.Name = val
}

// SetRegion sets the value of Region.
func (s *ProjectResponse) SetRegion(val string) {
	s.Region = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ProjectResponse) SetCreatedAt(val string) {
	s.CreatedAt = val
}

// Ref: #/components/schemas/SecretResponse
type SecretResponse struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// GetName returns the value of Name.
func (s SecretResponse) GetName() string {
	return s.Name
}

// GetValue returns the value of Value.
func (s SecretResponse) GetValue() string {
	return s.Value
}

// SetName sets the value of Name.
func (s *SecretResponse) SetName(val string) {
	s.Name = val
}

// SetValue sets the value of Value.
func (s *SecretResponse) SetValue(val string) {
	s.Value = val
}

// UpdateConfigForbidden is response for UpdateConfig operation.
type UpdateConfigForbidden struct{}

func (*UpdateConfigForbidden) updateConfigRes() {}

// UpdateConfigInternalServerError is response for UpdateConfig operation.
type UpdateConfigInternalServerError struct{}

func (*UpdateConfigInternalServerError) updateConfigRes() {}

type UpdateConfigOK struct{}

func (*UpdateConfigOK) updateConfigRes() {}

// Ref: #/components/schemas/UpdateFunctionBody
type UpdateFunctionBody struct {
	Name      OptString `json:"name"`
	Body      OptString `json:"body"`
	VerifyJwt OptBool   `json:"verify_jwt"`
}

// GetName returns the value of Name.
func (s UpdateFunctionBody) GetName() OptString {
	return s.Name
}

// GetBody returns the value of Body.
func (s UpdateFunctionBody) GetBody() OptString {
	return s.Body
}

// GetVerifyJwt returns the value of VerifyJwt.
func (s UpdateFunctionBody) GetVerifyJwt() OptBool {
	return s.VerifyJwt
}

// SetName sets the value of Name.
func (s *UpdateFunctionBody) SetName(val OptString) {
	s.Name = val
}

// SetBody sets the value of Body.
func (s *UpdateFunctionBody) SetBody(val OptString) {
	s.Body = val
}

// SetVerifyJwt sets the value of VerifyJwt.
func (s *UpdateFunctionBody) SetVerifyJwt(val OptBool) {
	s.VerifyJwt = val
}

// UpdateFunctionForbidden is response for UpdateFunction operation.
type UpdateFunctionForbidden struct{}

func (*UpdateFunctionForbidden) updateFunctionRes() {}

// UpdateFunctionInternalServerError is response for UpdateFunction operation.
type UpdateFunctionInternalServerError struct{}

func (*UpdateFunctionInternalServerError) updateFunctionRes() {}

// Ref: #/components/schemas/UpdatePgsodiumConfigBody
type UpdatePgsodiumConfigBody struct {
	RootKey string `json:"root_key"`
}

// GetRootKey returns the value of RootKey.
func (s UpdatePgsodiumConfigBody) GetRootKey() string {
	return s.RootKey
}

// SetRootKey sets the value of RootKey.
func (s *UpdatePgsodiumConfigBody) SetRootKey(val string) {
	s.RootKey = val
}
