// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

var _ Handler = UnimplementedHandler{}

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

// CreateFunction implements createFunction operation.
//
// Creates a function and adds it to the specified project.
//
// POST /v1/projects/{ref}/functions
func (UnimplementedHandler) CreateFunction(ctx context.Context, req CreateFunctionBody, params CreateFunctionParams) (r CreateFunctionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrganization implements createOrganization operation.
//
// Create an organization.
//
// POST /v1/organizations
func (UnimplementedHandler) CreateOrganization(ctx context.Context, req CreateOrganizationBody) (r CreateOrganizationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProject implements createProject operation.
//
// Create a project.
//
// POST /v1/projects
func (UnimplementedHandler) CreateProject(ctx context.Context, req CreateProjectBody) (r ProjectResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSecrets implements createSecrets operation.
//
// Creates multiple secrets and adds them to the specified project.
//
// POST /v1/projects/{ref}/secrets
func (UnimplementedHandler) CreateSecrets(ctx context.Context, req []CreateSecretBody, params CreateSecretsParams) (r CreateSecretsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteFunction implements deleteFunction operation.
//
// Deletes a function with the specified slug from the specified project.
//
// DELETE /v1/projects/{ref}/functions/{function_slug}
func (UnimplementedHandler) DeleteFunction(ctx context.Context, params DeleteFunctionParams) (r DeleteFunctionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSecrets implements deleteSecrets operation.
//
// Deletes all secrets with the given names from the specified project.
//
// DELETE /v1/projects/{ref}/secrets
func (UnimplementedHandler) DeleteSecrets(ctx context.Context, req []string, params DeleteSecretsParams) (r DeleteSecretsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConfig implements getConfig operation.
//
// Gets project's pgsodium config.
//
// GET /v1/projects/{ref}/pgsodium
func (UnimplementedHandler) GetConfig(ctx context.Context, params GetConfigParams) (r GetConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFunction implements getFunction operation.
//
// Retrieves a function with the specified slug and project.
//
// GET /v1/projects/{ref}/functions/{function_slug}
func (UnimplementedHandler) GetFunction(ctx context.Context, params GetFunctionParams) (r GetFunctionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFunctions implements getFunctions operation.
//
// Returns all functions you've previously added to the specified project.
//
// GET /v1/projects/{ref}/functions
func (UnimplementedHandler) GetFunctions(ctx context.Context, params GetFunctionsParams) (r GetFunctionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrganizations implements getOrganizations operation.
//
// Returns a list of organizations that you currently belong to.
//
// GET /v1/organizations
func (UnimplementedHandler) GetOrganizations(ctx context.Context) (r GetOrganizationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProjects implements getProjects operation.
//
// Returns a list of all projects you've previously created.
//
// GET /v1/projects
func (UnimplementedHandler) GetProjects(ctx context.Context) (r []ProjectResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSecrets implements getSecrets operation.
//
// Returns all secrets you've previously added to the specified project.
//
// GET /v1/projects/{ref}/secrets
func (UnimplementedHandler) GetSecrets(ctx context.Context, params GetSecretsParams) (r GetSecretsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateConfig implements updateConfig operation.
//
// Updates project's pgsodium config. Updating the root_key can cause all data encrypted with the
// older key to become inaccessible.
//
// PUT /v1/projects/{ref}/pgsodium
func (UnimplementedHandler) UpdateConfig(ctx context.Context, req UpdatePgsodiumConfigBody, params UpdateConfigParams) (r UpdateConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateFunction implements updateFunction operation.
//
// Updates a function with the specified slug and project.
//
// PATCH /v1/projects/{ref}/functions/{function_slug}
func (UnimplementedHandler) UpdateFunction(ctx context.Context, req UpdateFunctionBody, params UpdateFunctionParams) (r UpdateFunctionRes, _ error) {
	return r, ht.ErrNotImplemented
}
