// Code generated by ogen, DO NOT EDIT.
package api

type CreateFunctionRes interface {
	createFunctionRes()
}

type CreateOrganizationRes interface {
	createOrganizationRes()
}

type CreateSecretsRes interface {
	createSecretsRes()
}

type DeleteFunctionRes interface {
	deleteFunctionRes()
}

type DeleteSecretsRes interface {
	deleteSecretsRes()
}

type GetConfigRes interface {
	getConfigRes()
}

type GetFunctionRes interface {
	getFunctionRes()
}

type GetFunctionsRes interface {
	getFunctionsRes()
}

type GetOrganizationsRes interface {
	getOrganizationsRes()
}

type GetSecretsRes interface {
	getSecretsRes()
}

type UpdateConfigRes interface {
	updateConfigRes()
}

type UpdateFunctionRes interface {
	updateFunctionRes()
}
